version: 2.1

jobs:
  update-map:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y jq
            pip install googlemaps
            curl https://raw.githubusercontent.com/ravenac95/super-fast-cli-gmail-cli/master/googlemaps.py --output googlemaps.py

      - run:
          name: Update map
          command: |
            # Set your Planning Center People API key
            PLANNING_CENTER_API_KEY="your_api_key_here"

            # Set your Google Maps API key
            GOOGLE_MAPS_API_KEY="your_api_key_here"

            # Make a request to the Planning Center People API to retrieve a list of people with their zip codes
            people=$(curl -s "https://api.planningcenteronline.com/people/v2/people?per_page=1000&include=addresses&fields%5Baddresses%5D=zip&access_token=$PLANNING_CENTER_API_KEY")

            # Extract the zip codes from the response and store them in a list
            zip_codes=$(echo "$people" | jq -r '.data[].attributes.addresses[].zip' | sort -u)

            # Authenticate with the Google Maps API using your API key
            maps_client=$(googlemaps --client-id "$GOOGLE_MAPS_API_KEY")

            # Loop through each zip code and add a marker for each location on the map
            for zip_code in $zip_codes; do
              # Use the Google Maps API to convert the zip code into a latitude and longitude
              location=$(echo "$maps_client" --geocode="$zip_code" | jq -r '.results[0].geometry.location | .lat, .lng')

              # Update the existing map with the marker for the zip code location
              echo "$maps_client" --id="your_map_id_here" --update --marker="$location"
            done